---
title: "strings_and_factors"
author: "Leonor Rui"
date: "2024-10-15"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(rvest)
library(p8105.datasets)
library(stringr)
library(tidyverse)

```

## Let's do strings

```{r}
string_vec = c("my", "name", "is", "leonor")

str_detect(string_vec, "leonor")

str_replace(string_vec, "leonor", "Leonor")

str_replace(string_vec, "e", "E")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

# anywhere in the string
str_detect(string_vec, "i think")

## ^ beginning of a line
str_detect(string_vec, "^i think")

## $ end of line
str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

## case sensitive
str_detect(string_vec, "pumpkin")

str_detect(string_vec, "Pumpkin")

str_detect(string_vec, "[Pp]umpkin")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

## connected number and letter
str_detect(string_vec, "[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

## anything between 7 and 11
str_detect(string_vec, "7.11")
```

How things start to get really strange

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

## indicate character instead of open bracket
str_detect(string_vec, "\\[")
```

## Factors...

```{r}
sex_vec = factor(c("male", "male", "female", "female"))

as.numeric(sex_vec)
```

do some releveling ...

```{r}
## reorder levels
sex_vec = fct_relevel(sex_vec, "male")

as.numeric(sex_vec)
```

Revisit examples

```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

Get the pieces I actually need

```{r}
marj_use_df = 
  drug_use_html |>
  html_table() |>
  first() |>
  slice(-1) |>
  select(-contains("P value")) |>
  pivot_longer(
    cols = -State,
    names_to = "age_year",
    values_to = "percent"
  ) |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_remove(percent, "[a-z]$"),
    percent = as.numeric(percent)
  )
```

```{r}
marj_use_df |>
  filter(age == "12-17",
         !(State %in% c("Total U.S.", "South"))) |>
  mutate(
    State = fct_reorder(State, percent)
  ) |>
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## NYC Restaurant Inspections

```{r}
data("rest_inspec")
```

```{r}
rest_inspec |>
  count(boro, grade) |>
  pivot_wider(
    names_from = grade,
    values_from = n)
```

```{r}
rest_inspec = rest_inspec |>
  filter(str_detect(grade, "[A-C]"),
         !boro == "Missing"
        )
```

```{r}
rest_inspec |>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba, "Pizza")) |>
  mutate(boro = fct_infreq(boro)) |>
  ggplot(aes(x = boro)) +
  geom_bar()

## str_replace return the levels in the alphabetical order again
rest_inspec |>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba, "Pizza")) |>
  mutate(boro = fct_infreq(boro),
         boro = str_replace(boro, "MANHATTAN", "THE CITY")) |>
  ggplot(aes(x = boro)) +
  geom_bar()

## fct_recode only changes the name
rest_inspec |>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba, "Pizza")) |>
  mutate(boro = fct_infreq(boro),
         boro = fct_recode(boro, "THE CITY" = "MANHATTAN")) |>
  ggplot(aes(x = boro)) +
  geom_bar()

rest_inspec |>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba, "Pizza")) |>
  mutate(boro = fct_relevel(boro, "STATEN ISLAND")) |>
  ggplot(aes(x = boro)) +
  geom_bar()
```

One last thing on factors...

Since levels in alphabetical order, the regression takes Bronx as the intercept
```{r}
rest_inspec |>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba, "Pizza")) |>
  lm(zipcode ~ boro, data = _)

rest_inspec |>
  mutate(dba = str_to_sentence(dba)) |>
  filter(str_detect(dba, "Pizza")) |>
  lm(zipcode ~ boro, data = _)
```










